# Generated by Django 3.2.8 on 2021-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211028_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gexing',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='个性签名'),
        ),
    ]
