# Generated by Django 3.2.8 on 2021-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211028_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
