# Generated by Django 3.2.8 on 2021-10-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default.jpg', max_length=50, upload_to='images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
